# Netlify configuration
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing - redirect everything to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for caching and security
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
